import type { EntityId } from "@/types/api";

export type Student = {
  id?: EntityId;
  uuid?: EntityId;
  nama: string;
  nama_panggilan?: string;
  email?: string;
  nis?: string;
  nisn?: string;
  tempat_lahir?: string;
  tanggal_lahir?: string;
  agama?: string;
  anak_ke?: number;
  jenis_kelamin?: string;
  nama_ayah?: string;
  pekerjaan_ayah?: string;
  nama_ibu?: string;
  pekerjaan_ibu?: string;
  no_hp_orangtua?: string;
  alamat_orangtua_jalan?: string;
  alamat_orangtua_kecamatan?: string;
  alamat_orangtua_kabupaten?: string;
  alamat_orangtua_provinsi?: string;
  nama_wali?: string;
  pekerjaan_wali?: string;
  no_hp_wali?: string;
  alamat_wali_jalan?: string;
  alamat_wali_kecamatan?: string;
  alamat_wali_kabupaten?: string;
  alamat_wali_provinsi?: string;
  tanggal_diterima?: string;
  catatan_guru?: string;
  status?: string;
  class_id?: EntityId;
  school_id?: EntityId;
};
